services:

  nestjs-postgres:
    container_name: nestjs-postgres
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - ./.docker/postgres:/docker-entrypoint-initdb.d
    #  - ./.docker/dbdata:/var/lib/postgresql/data

  nestjs-app:
    container_name: nestjs-app
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - .:/home/node/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
